version: "3.5"

services:
  localstack:
    # "${LOCALSTACK_DOCKER_NAME-localstack_main}" means docker-compose.yml will refer to the value of variable called LOCALSTACK_DOCKER_NAME in a .env file. Otherwise the docker container is named "localstack_main".
    container_name: "localstack"
    # From 2020-07-11 onwards, the default image "localstack/localstack" in Docker Hub refers to the “light version”, which has some large dependency files like Elasticsearch removed
    # In case you need the full set of dependencies, the "localstack/localstack-full" image can be used instead
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      # Specify the services in a variable named SERVICES, otherwise localstack does not work...
      - SERVICES=s3,sqs
      - DEBUG=1
      - DEFAULT_REGION=eu-central-1
    volumes:
      - ./data/localstack:/var/lib/localstack/data/
    networks:
      - local-localstack-network

networks:
  local-localstack-network:
    driver: bridge
    name: local-merchant-network
